accelerator: cuda:1
out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: WN-chameleon
dataset:
  format: PyG-WikipediaNetwork
  name: chameleon
  task: node
  task_type: classification
  transductive: True
  split_mode: standard
  node_encoder: True
  node_encoder_name: LinearNode+RWSE
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_GraphormerBias:
  enable: False
  node_degrees_only: True
  num_spatial_types: 20
  num_in_degrees: 729
  num_out_degrees: 89
graphormer:
  use_graph_token: False
posenc_LapPE:
  enable: False
  eigen:
    laplacian_norm: none
    eigvec_norm: L2
    max_freqs: 4
  model: DeepSet
  dim_pe: 4
  layers: 2
  n_heads: 4  # Only used when `posenc.model: Transformer`
  raw_norm_type: none
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  sampler: full_batch
#  sampler: saint_rw
#  batch_size: 32
  eval_period: 1
  enable_ckpt: False
#  ckpt_period: 100
model:
  type: SGFormer
  loss_fun: cross_entropy
  edge_decoding: dot
gt:
  layer_type: GCN+Transformer
  layers: 4
  n_heads: 3
  use_weight: True
  use_residual: True
  use_act: True
  dim_hidden: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.5
  attn_dropout: 0.5
  use_graph: True
  graph_weight: 0.2
  aggregate: add
  layer_norm: False
  batch_norm: False
gnn:
  head: node
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 96  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.2
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 5e-4
  base_lr: 0.0005
  max_epoch: 400
  scheduler: cosine_with_warmup
  num_warmup_epochs: 20
