accelerator: cuda:0
dataset:
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: DummyEdge
  format: PyG-WebKB
  name: wisconsin
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: LinearNode
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
gnn:
  act: gelu
  agg: mean
  batchnorm: true
  dim_inner: 96
  dropout: 0.1
  head: node
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
gt:
  attn_dropout: 0.3
  dim_hidden: 96
  dropout: 0.5
  layers: 3
  n_heads: 2
metric_best: accuracy
model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: M3Dphormer
m3dphormer:
  global_nodes_per_class: 1
  learn_global: false
  local_type: GAT
  norm_pos: pre
  norm_type: rms
  num_clusters: 128
  use_global_aux_loss: true
  global_aux_loss_weight: 1.0
  use_cache: false
  use_res: true
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 300
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.0001
out_dir: results
train:
  enable_ckpt: false
  eval_period: 1
  mode: custom
  sampler: full_batch
wandb:
  project: wisconsin
  use: false
