dataset:
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: DummyEdge
  format: PyG-Actor
  name: none
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: LinearNode+GraphormerBias
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
gnn:
  act: gelu
  agg: mean
  batchnorm: true
  dim_inner: 64
  dropout: 0.2
  head: node
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
graphormer:
  attention_dropout: 0.0
  dropout: 0.2
  embed_dim: 64
  input_dropout: 0.0
  mlp_dropout: 0.2
  num_heads: 4
  num_layers: 2
  use_graph_token: false
metric_best: accuracy
model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: Graphormer
optim:
  base_lr: 0.0005
  clip_grad_norm: true
  clip_grad_norm_value: 5.0
  max_epoch: 200
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1e-5
out_dir: results
posenc_GraphormerBias:
  enable: true
  num_in_degrees: 729
  num_out_degrees: 89
  num_spatial_types: 20
train:
  enable_ckpt: false
  eval_period: 5
  mode: custom
  sampler: full_batch
wandb:
  project: actor
  use: false
