accelerator: cuda:4
dataset:
  edge_encoder: true
  edge_encoder_bn: false
  edge_encoder_name: Bond
  format: OGB
  name: ogbg-molpcba
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: Atom+GraphormerBias
  split_mode: standard
  task: graph
  task_type: classification
  transductive: false
gnn:
  act: gelu
  agg: mean
  batchnorm: true
  dim_inner: 64
  dropout: 0.2
  head: san_graph
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
graphormer:
  attention_dropout: 0.0
  dropout: 0.2
  embed_dim: 64
  input_dropout: 0.0
  mlp_dropout: 0.2
  num_heads: 4
  num_layers: 2
  use_graph_token: false
metric_best: auc
model:
  edge_decoding: dot
  graph_pooling: mean
  loss_fun: cross_entropy
  type: Graphormer
optim:
  base_lr: 0.0005
  clip_grad_norm: true
  clip_grad_norm_value: 5.0
  max_epoch: 100
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 1e-5
out_dir: results
posenc_GraphormerBias:
  enable: true
  num_in_degrees: 729
  num_out_degrees: 89
  num_spatial_types: 20
train:
  batch_size: 32
  ckpt_period: 100
  enable_ckpt: false
  eval_period: 1
  mode: custom
  sampler: full_batch
wandb:
  project: molpcba
  use: false
