accelerator: cuda:0
dataset:
  edge_encoder: false
  edge_encoder_bn: false
  edge_encoder_name: DummyEdge
  format: PyG-Planetoid
  name: pubmed
  node_encoder: true
  node_encoder_bn: false
  node_encoder_name: LinearNode
  split_mode: standard
  task: node
  task_type: classification
  transductive: true
gnn:
  act: relu
  agg: mean
  batchnorm: true
  dim_inner: 96
  dropout: 0.5
  head: node
  layers_post_mp: 1
  layers_pre_mp: 0
  normalize_adj: false
gt:
  attn_dropout: 0.5
  dim_hidden: 96
  dropout: 0.5
  graph_weight: 0.8
  layers: 3
  n_heads: 1
metric_best: accuracy
model:
  edge_decoding: dot
  loss_fun: cross_entropy
  type: GTSNT
optim:
  base_lr: 0.001
  clip_grad_norm: true
  max_epoch: 300
  num_warmup_epochs: 10
  optimizer: adamW
  scheduler: cosine_with_warmup
  weight_decay: 0.001
out_dir: results
train:
  enable_ckpt: false
  eval_period: 1
  mode: custom
  sampler: full_batch
wandb:
  project: pubmed
  use: false
